name:                 fuyu-gpio
version:              0.1.0.0
visibility:           public
id:                   fuyu-gpio-0.1.0.0-inplace
key:                  fuyu-gpio-0.1.0.0-inplace
license:              GPL-2.0-only
maintainer:           springtrap9397@gmail.com
author:               Bass
synopsis:             Bindings para libgpiod en Haskell.
category:             System
abi:                  inplace
exposed:              True
exposed-modules:      Fuyu.GPIO Fuyu.GPIO.Unsafe
hidden-modules:       Fuyu.GPIO.Internal
import-dirs:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/build

library-dirs:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/build

library-dirs-static:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/build

dynamic-library-dirs:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/build

data-dir:             /app/fuyu-gpio/.
hs-libraries:         HSfuyu-gpio-0.1.0.0-inplace
extra-libraries:      gpiod
depends:              base-4.20.2.0-f8cf unix-2.8.7.0-f9a0
haddock-interfaces:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/doc/html/fuyu-gpio/fuyu-gpio.haddock

haddock-html:
    /app/fuyu-gpio/dist-newstyle/build/aarch64-linux/ghc-9.10.3/fuyu-gpio-0.1.0.0/doc/html/fuyu-gpio
